@startuml klassediagram

title Klassediagram - Watchlist


class Movie {
    -String name
    -int year
    -String description
    -List<String> keywords
    -double rating
    -int ratingCount
    -List<String> actors
    -List<String> directors
    -List<String> genre
    -String imageUrl
    -String thumbUrl
    -int userRating
    +String ratingCountToString()
    +boolean equals(Object o)
    +int hashCode()
    +String toString()
    +void rate(int rating)
    -void updateRating(int oldValue, int newValue)
}

class Watchlist {
    -List<Movie> list
    +void addMovie(Movie movie)
    +void removeMovie(Movie movie)
    +void sortWatchlistByName()
    +void sortWatchlistByYear()
    +void sortWatchlistByRating()
    +List<Movie> filterWatchlist(String string)
}

class User {
    -String name
    -List<Movie> movies
    +ArrayList<String> getMovieNames()
    +void watchMovie(Movie movie)
    +boolean unwatchMovie(String title)
    +void sortUserlistByName()
    +void sortUserlistByYear()
    +void sortUserlistByRating()
}

class SaveLoadHandler {
    -Path saveFilePath
    -ObjectMapper objectMapper
    -ObjectWriter objectWriter
    -String serverUrl
    +List<Movie> loadUserList()
    +List<Movie> loadUserListHttp(String username)
    +void saveUserList(List<Movie> movieList)
    +void saveUserListHttp(String username, List<Movie> movieList)
    +void setSaveFile(String filename)
}

class WatchlistPersistence {
    -String serverUrl
    -ObjectMapper objectMapper
    +List<Movie> loadMovieList(String movieResource)
    +List<Movie> loadMovieListHttp()
}

class WatchlistApp {
    +void start(final Stage primaryStage)
    +{static} void main(String[] args)
}

class WatchlistController {
    -User user
    -Watchlist list
    -Watchlist initialList
    -SaveLoadHandler saveLoadHandler
    -WatchlistPersistence persistence
    -Movie activeBrowserMovie
    -Movie activeProfileMovie
    -ChangeListener<Movie> browserChangeListener
    -ChangeListener<Movie> profileChangeListener
    +void initialize()
    -ChangeListener<Movie> generateListener(ListView<Movie> listView, TextField textField, Button button)
    +void setUsername(String name)
    -void handleLoadResourceList(String resource)
    -void handleLoadUserList()
    -void handleSaveUserList()
    void handleWatchMovie()
    +void watchMovie(Movie movie)
    +void changeSortingInBrowser()
    void handleUnwatchMovie()
    +void changeSortingInProfile()
    -void updateGui()
    -void updateBrowserGui()
    -void updateMoviebrowser()
    -void updateProfileGui()
    -void updateWatchedMovies()
    -void showInfo(Movie movie, Pane pane)
    -void updateRating(int value)
    -void setListeners(ListView<Movie> listView)
    +void addFiltertoWatchlist(String filter)
}
note top
    I denne klassen er det i tillegg en mengde attributter tilknyttet FXML.
    Det ble tatt en vurdering på at det var best å droppe disse fra klassediagrammet.
end note

class LoginController {
    -Button exit
    -Button login
    -TextField name
    -Label invalidInput
    -Label logo
    +void initialize()
    +void onSubmit()
}

class WatchlistRestApplication {
    +{static} void main(String[] args)
}

class WatchlistRestController {
    -WatchlistRestService watchlistRestService
    +List<Movie> getMovies()
    +List<Movie> getUserList(String username)
    +Boolean putUserList(String username, String jsonString)
}

class WatchlistRestService {
    -Watchlist watchlist
    -ObjectMapper objectMapper
    -SaveLoadHandler saveLoadHandler
    -String movieResource
    +void handleLoadResourceList(String filename)
    +List<Movie> handleLoadUserList(String username)
    +void handleSaveUserList(String username, String jsonString)
}

@enduml